### ISSUE TITLE
Skip java step on onboarding if it's successfully detected

### ISSUE THREAD

**Issue by Prospector** [modrinth/theseus#148]
### Is your suggested enhancement related to a problem? Please describe.

This step is kinda unnecessary if you already have java installed and it's detected. Maybe it shouldn't skip it but instead show the current java it's using and have an option to install a new one or change it to a different installation?

![image](https://github.com/modrinth/theseus/assets/6166773/c5643977-daae-4519-aa9f-197c0ad51d04)

**Comment by fakechips** [comment]
i would like to add to this that it can be quite overwhelming for someone who has no knowledge of java versions or anything because they wont know if they are installing something they already have, even though there is a "Use Existing Installation" button it can still be very unclear for a new player installing the launcher what to do.

**Comment by CodexAdrian** [comment]
This is fixed in #347
