### ISSUE TITLE
New instances download an older version of Quilt by default

### ISSUE THREAD

**Issue by cootshk** [modrinth/theseus#294]
### Describe the bug

Chosing Quilt without chosing a version will make it download Quilt 0.17.9-beta.1

Quilt 0.19.1 is the latest versoin

### Steps to reproduce

Make a new instance
Select Quilt
Don't manually specify a version

### Expected behavior

Downloads Quilt 0.19.1

### Additional context

Some mods will crash because of an old quilt loader

**Comment by NitrolessWasTaken** [comment]
to add to this, this is probably because the quilt versions arent listed in order for some reason, 0.17.9-beta.1 being at the top of the list
i think this is the actual bug, because the launcher selecting the topmost version is intended behaviour, except in this case the highest version in the list isnt the newest one

![image](https://github.com/modrinth/theseus/assets/81432274/7f3ab68b-fc68-4c23-a257-2132a5c16ab9)

also beta versions are all over the place 

![image](https://github.com/modrinth/theseus/assets/81432274/c8a8eba0-a5c2-441b-97a7-1145b59cb7fe)

**Comment by Dyvinia** [comment]
the latest quilt beta is 0.19.2-beta7 from what i can tell, and it doesnt seem to show up in the dropdown at all here, while it does in prism for example 
![image](https://github.com/modrinth/theseus/assets/13797470/9157ade0-0f2b-4097-8224-4adad1debfd1)

**Comment by bappitybup** [comment]
When selecting Quilt Loader 0.20.0-beta.2 my game version defaults to 1.19.2.

When I try to select 1.20.1, the version list will not show it at the top of the scrollbar, however I can select it if I use arrow keys then the space key
![image](https://github.com/modrinth/theseus/assets/12457072/0b642007-3bd0-4661-a835-b0da471e7e93)

the top of the context menu appears to be cut off.

**Comment by Geometrically** [comment]
this is fixed. the dropdown issue is a separate problem

**Comment by ZesilinaNewborn** [comment]
This is still not fixed as of the latest version of the launcher, it still downloads an old version of Quilt if you don't specify the version and the versions in the list are not sorted correctly still

**Comment by Dyvinia** [comment]
I have the same issue still
