### ISSUE TITLE
Color log lines according to their contents

### ISSUE THREAD

**Issue by HyperSoop** [modrinth/theseus#387]
### Is your suggested enhancement related to a problem? Please describe.

I'm so used to Prism Launcher I want Modrinth App to also color highlight log lines. This helps spot out things going wrong quicker.

### Describe the solution you'd like

Color warns yellow and errors red.

**Comment by User4716** [comment]
YES YES I WANT this too, sorry got a little excited there.

But it's true, it speeds troubleshooting and makes the log cleaner, also it's just good to have it!
(The default Minecaft launcher log output doesn't have colors if you use a modded platform so I'm kinda used to the white text :D)

‎ 
`✨A cool idea:`
Also because the Live log looks so much like a CMD window or a Minecraft server console, it would be super cool if I could send commands or use the chat directly from the Live log (I would need to be in a world for this to work of course)

**Comment by User4716** [comment]
#579
I included this same idea in my issue, even though it seems like just extra work for the developers, I had the same idea and put some cool pictures in that issue + a few extra ideas I had
