### ISSUE TITLE
Launcher: Support Microsoft account authentication

### ISSUE THREAD

**Issue by enderger** [modrinth/theseus#4]
Currently, there is no support for authenticating via Microsoft accounts. This makes usage difficult especially with the migration push being underway.

**Comment by ramonGonzEdu** [comment]
Note that this will require binaries due to how microsoft authentication requires an app token (which should be private), so this should either be a [feature], or designed in a way where it'll print a nice error when the ms api token isn't supplied. (You could also do direct microsoft logins, but they are much more unsafe, and I don't think many people would willingly put their ms password into some random app)

**Comment by ramonGonzEdu** [comment]
Note that this will require binaries due to how microsoft authentication requires an app token (which should be private), so this should either be a [feature], or designed in a way where it'll print a nice error when the ms api token isn't supplied. (You could also do direct microsoft logins, but they are much more unsafe, and I don't think many people would willingly put their ms password into some random app)

**Comment by enderger** [comment]
> Note that this will require binaries due to how microsoft authentication requires an app token (which should be private), so this should either be a [feature], or designed in a way where it'll print a nice error when the ms api token isn't supplied. (You could also do direct microsoft logins, but they are much more unsafe, and I don't think many people would willingly put their ms password into some random app)

This is actually untrue in our very specific case. Since we are dealing with Minecraft, we have to use it’s login system as demonstrated by [this launcher](https://github.com/xmdhs/gomclauncher/blob/master/auth/msauth.go).

**Comment by theofficialgman** [comment]
microsoft changed their wording in their own terms of use a few weeks ago. The statement about the application (client) id needing to be confidential has been removed
https://docs.microsoft.com/en-us/legal/microsoft-identity-platform/terms-of-use

**Comment by enderger** [comment]
From the look of things, we need to add code to our auth server which holds and uses our client secret for MS logins.

**Comment by theofficialgman** [comment]
no, the client id is intended and expected to be on the user device side for client side authentication. Its own every other launcher implements it currently

**Comment by enderger** [comment]
I meant the client secret, sorry. That should be on the server, while the
client id is not a secret and should be stored client side.
