### ISSUE TITLE
New instances don't respect filter

### ISSUE THREAD

**Issue by srnyx** [modrinth/theseus#689]
### Describe the bug

When creating a new instance, it goes to the end of the list of instances instead of following into place according to the set "Sort by" filter. When changing the filter, it still doesn't move

### Steps to reproduce

1. Set filter to something (such as `Game version`)
2. Create a new instance that should be expected to go at the beginning or someplace specific
3. The new instance will be at the very end, even when changing the filter to something else then back to the original one

### Expected behavior

The new instance should be placed among existing instances according to the "Sort by" filter instead of at the very end

### Additional context

The new instance still moves around when changing the "Soty by" sometimes, but if changing it back to the original filter, it still goes to the very end, it also appears restarting the launcher doesn't work either, so maybe this is an entirely different bug??
Here's a video of it (first half, second half is #688): https://max-is.very-stinky.com/Modrinth_App_bCEqjwYBXF.mp4

**Comment by thesuzerain** [comment]
Is this referring to the individual instances within a group? Does this occur with any other sorting method? I can't reproduce this with any other sorting method other than the #688 one.

or is this issue referring to the category groups themselves, after you've done a 'Group by'? So that the entire category of 1.8.8 is between 1.20.0 and 1.20.1 in the video you show when it shouldn't be? Juyst want to make sure I am 100% sure which this issue is for
