### ISSUE TITLE
Being able to rename profiles

### ISSUE THREAD

**Issue by RealmKebab** [modrinth/theseus#691]
### Describe the solution you'd like

Like in Prism Launcher, you can rename profile names without actually changing the names of the folder
I'd want that here so I can rename my profiles from some weird gibberish to something normal

**Comment by thesuzerain** [comment]
I assume you are referring to the visible name and not the internal name (because the latter is simply the folder name). 

You should be able to do that on a modpack's options. so click the profile -> options -> change the name (in the first section, under where you change the icon). 

If that field is disabled, then it is because it is a paired modpack (ie: linked to a modrinth modpack), in which case you can unpair it at the bottom of the options page first, then change the name. 

Is that what are you are referring to, or am I potentially misunderstanding?

**Comment by RealmKebab** [comment]
Yes

**Comment by thesuzerain** [comment]
great! :)
