### ISSUE TITLE
[Linux] App doesn't boot

### ISSUE THREAD

**Issue by Birwi** [modrinth/theseus#752]
### Is your suggested enhancement related to a problem? Please describe.

On Modrinth website I've installed the Deb package but after installing and trying to run it, it doesn't boot.

OS: Ubuntu 22.04.

### Describe the solution you'd like

App should boot

### Additional context

I've also installed the AppImage and it does boot up with that, but I would like to use the Deb package.

**Comment by perryBunn** [comment]
So i had a similar issue and after going through the logs for the failed execution it was due to libssl.so.1.1 not being found.
```log
Failed to start app-gnome-modrinth\x2dapp-2828.scope - Application launched by gnome-shell.
app-gnome-modrinth\x2dapp-2828.scope: Failed with result 'resources'.
app-gnome-modrinth\x2dapp-2828.scope: Failed to add PIDs to scope's control group: No such process
app-gnome-modrinth\x2dapp-2828.scope: Couldn't move process 2828 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-modrinth\x2dapp-2828.scope': No such process
/usr/bin/modrinth-app: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I found a stack overflow post that resolved this buy grabbing the lib from a package archive. --> https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

Running the following in the terminal should install the library and fix the issue.
```bash
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```

**Comment by Birwi** [comment]
It worked, thank you!
