### ISSUE TITLE
Forge 1.12.2 Doesnt launch at all

### ISSUE THREAD

**Issue by cad3264** [modrinth/theseus#843]
### Describe the bug

Upon clicking on a installation with forge 1.12.2, it instantly stops.

### Steps to reproduce

1. Make a new forge 1.12.2 instance
2. Launch it
3. It instantly exits.

### Expected behavior

It should open minecraft forge 1.12.2

### System information

Windows 10, Newest Modrinth App

**Comment by Cosmiinox** [comment]
also have issue

**Comment by wlad26** [comment]
Can't reproduce on Windows 11 and App version 0.6.3

**Comment by triphora** [comment]
Unable to reproduce

**Comment by Cod1ngGamer** [comment]
I can reproduce this bug, because it happens every time I try to load up 1.12.2 even if there are no actual mods in the instance. As long as it's version 1.12.2, and it's set to anything but vanilla, it instantly crashes the moment I press the play button. I've been having to use CurseForge to play SRP, and it's honestly kind of annoying.

**Comment by Cod1ngGamer** [comment]
ig its something to do with 1.12 in general (or just old versions)
